### ISSUE TITLE
Can't compile from git

### ISSUE THREAD

**Issue by McFlip** [pst-format/libpst#12]
I'm building with Fedora after cloning this git repo.
I get the following error when running `make -f *cvs`

```
checking whether to build the libpst python interface... yes
./configure: line 26386: syntax error near unexpected token `>'
./configure: line 26386: `    AX_PYTHON_DEVEL(>= '$PYTHON_VERSION')'
make: *** [Makefile.cvs:12: all] Error 2
```

I actually don't care about the Python interface so I changed the Makefile.cvs file to add the flag `--enable-python=no` to the ./configure command and I still get the same problem.

```
checking whether to build the libpst python interface... no
./configure: line 26386: syntax error near unexpected token `>'
./configure: line 26386: `    AX_PYTHON_DEVEL(>= '$PYTHON_VERSION')'
make: *** [Makefile.cvs:12: all] Error 2
```

**Comment by pabs3** [comment]
Do you have autoconf-archive installed?

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by McFlip** [comment]
That fixed it along with installing the boost python devel package. Next I had to install `xmlto`. Maybe I'm a noob but I had a hard time figuring out all the dependencies. I think I'll create a DOCKER file for compiling. I only found 1 image on Docker Hub for libpst from 6 years ago and it had a package installed, not a container for building. I will send you the DOCKER file if I get it working.

**Comment by pabs3** [comment]
Sorry, the project does need better documentation, probably something
more like the one I did for mpv-mpris. Made a note in my TODO.

https://github.com/hoyon/mpv-mpris

I'd prefer not to include downstream packaging like Dockerfiles or
debian/ directories or RPM .spec files within the upstream projects,
those should be added to the package repositories they are for, like
Docker Hub or Debian or Fedora.

PS: I'm interested to hear about the situation you are using libpst in.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by McFlip** [comment]
Understood. I finally got around to creating a [Dockerfile](https://github.com/McFlip/enigma/blob/main/readpst/Dockerfile).

I am specifically using readpst in my forensic tool for batch deciphering encrypted emails. I extract the PSTs to a temp filesystem then iterate through them using Go's "mime", "mime/multipart", & "net/mail" libraries.
