### ISSUE TITLE
Folder with slash error

### ISSUE THREAD

**Issue by j4k0xb** [pst-format/libpst#13]
Output of readpst:

> Processing Folder "A/B"
> mk_separate_dir: Cannot create directory A/B: Invalid argument

Please also escape forward slashes

**Comment by pabs3** [comment]
Could you attach a sample PST file that can be used to reproduce this?

**Comment by j4k0xb** [comment]
nvm seems to have been fixed after building from source, the latest released version 0.6.76-1 (`apt install pst-utils` on mint) was quite old
